// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartTradeLib.Persistence;

#nullable disable

namespace SmartTradeLib.Migrations
{
    [DbContext(typeof(SmartTradeContext))]
    [Migration("20240311143552_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartTradeLib.Entities.Adress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostumerEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Door")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CostumerEmail");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostumerEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CostumerEmail");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserEmail");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.BizumInfo", b =>
                {
                    b.Property<string>("TelephonNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CostumerEmail")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TelephonNumber");

                    b.HasIndex("CostumerEmail");

                    b.ToTable("Bizums");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.CreditCardInfo", b =>
                {
                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardHolder")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostumerEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExpirationDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardNumber");

                    b.HasIndex("CostumerEmail");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("ShippingCost")
                        .HasColumnType("real");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.PayPalInfo", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CostumerEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.HasIndex("CostumerEmail");

                    b.ToTable("PayPals");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("SellerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Validated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AdminEmail");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerEmail");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Certification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("EcologicPrint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("Validated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AdminEmail");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SmartTradeLib.Entities.User", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("User");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Book", b =>
                {
                    b.HasBaseType("SmartTradeLib.Entities.Product");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Book");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Clothing", b =>
                {
                    b.HasBaseType("SmartTradeLib.Entities.Product");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Clothing");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Nutrition", b =>
                {
                    b.HasBaseType("SmartTradeLib.Entities.Product");

                    b.Property<string>("Allergens")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Calories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carbohydrates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fats")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proteins")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Nutrition");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Toy", b =>
                {
                    b.HasBaseType("SmartTradeLib.Entities.Product");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Products", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("Toy_Brand");

                            t.Property("Material")
                                .HasColumnName("Toy_Material");
                        });

                    b.HasDiscriminator().HasValue("Toy");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Admin", b =>
                {
                    b.HasBaseType("SmartTradeLib.Entities.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Costumer", b =>
                {
                    b.HasBaseType("SmartTradeLib.Entities.User");

                    b.Property<int>("BillingAddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("BillingAddressId");

                    b.ToTable("User", t =>
                        {
                            t.Property("DNI")
                                .HasColumnName("Costumer_DNI");
                        });

                    b.HasDiscriminator().HasValue("Costumer");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Seller", b =>
                {
                    b.HasBaseType("SmartTradeLib.Entities.User");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Seller");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Adress", b =>
                {
                    b.HasOne("SmartTradeLib.Entities.Costumer", null)
                        .WithMany("Adresses")
                        .HasForeignKey("CostumerEmail");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Alert", b =>
                {
                    b.HasOne("SmartTradeLib.Entities.Costumer", null)
                        .WithMany("Orders")
                        .HasForeignKey("CostumerEmail");

                    b.HasOne("SmartTradeLib.Entities.Product", "Product")
                        .WithMany("Alerts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartTradeLib.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.BizumInfo", b =>
                {
                    b.HasOne("SmartTradeLib.Entities.Costumer", null)
                        .WithMany("BizumAccounts")
                        .HasForeignKey("CostumerEmail");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.CreditCardInfo", b =>
                {
                    b.HasOne("SmartTradeLib.Entities.Costumer", null)
                        .WithMany("CreditCards")
                        .HasForeignKey("CostumerEmail");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Offer", b =>
                {
                    b.HasOne("SmartTradeLib.Entities.Post", "Post")
                        .WithMany("Offers")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.PayPalInfo", b =>
                {
                    b.HasOne("SmartTradeLib.Entities.Costumer", null)
                        .WithMany("PayPalAccounts")
                        .HasForeignKey("CostumerEmail");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Post", b =>
                {
                    b.HasOne("SmartTradeLib.Entities.Admin", null)
                        .WithMany("ValidatedPosts")
                        .HasForeignKey("AdminEmail");

                    b.HasOne("SmartTradeLib.Entities.Product", null)
                        .WithMany("Posts")
                        .HasForeignKey("ProductId");

                    b.HasOne("SmartTradeLib.Entities.Seller", "Seller")
                        .WithMany("Posts")
                        .HasForeignKey("SellerEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Product", b =>
                {
                    b.HasOne("SmartTradeLib.Entities.Admin", null)
                        .WithMany("ValidatedProducts")
                        .HasForeignKey("AdminEmail");

                    b.HasOne("SmartTradeLib.Entities.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Costumer", b =>
                {
                    b.HasOne("SmartTradeLib.Entities.Adress", "BillingAddress")
                        .WithMany()
                        .HasForeignKey("BillingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingAddress");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Post", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Product", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Posts");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Admin", b =>
                {
                    b.Navigation("ValidatedPosts");

                    b.Navigation("ValidatedProducts");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Costumer", b =>
                {
                    b.Navigation("Adresses");

                    b.Navigation("BizumAccounts");

                    b.Navigation("CreditCards");

                    b.Navigation("Orders");

                    b.Navigation("PayPalAccounts");
                });

            modelBuilder.Entity("SmartTradeLib.Entities.Seller", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
